### ISSUE TITLE
 cannot import name 'Model' from 'g4f' 

### ISSUE THREAD

**Issue by firashacker** [MIDORIBIN/langchain-gpt4free#1]
Traceback (most recent call last):
  File "/home/firas/Data/firas/tools/chatgpt-clone/main.py", line 1, in <module>
    from g4f import Provider, Model
ImportError: cannot import name 'Model' from 'g4f' (/home/firas/Data/firas/tools/chatgpt-clone/venv/lib/python3.11/site-packages/g4f/__init__.py)

**Comment by biegaj** [comment]
> 
`    llm: LLM = G4FLLM(
        model='gpt-4',
        provider=Provider.ChatgptAi,
    )
`

**Comment by MIDORIBIN** [comment]
Thanks for the report.
I'll get right on it.

**Comment by MIDORIBIN** [comment]
@biegaj 
It has been fixed.
If you find another problem, please report it.
