### ISSUE TITLE
KeyError: 'message'

### ISSUE THREAD

**Issue by muhammadhasnain100** [MIDORIBIN/langchain-gpt4free#3]
When implementing your provided code for summarization, I encountered an error in response. The error message was as follows:
KeyError: 'message'
I have attempted various solutions to rectify this issue, but I have not been successful in resolving it. I kindly request your assistance in addressing this matter.

Here is the code that I have utilized:
llm = G4FLLM(
        model=models.gpt_35_turbo,
        provider=Provider.Aichat,
    )

def summarize_pdf(pdf_file_path):
    loader = PyPDFLoader(pdf_file_path)
    docs = loader.load_and_split()
    chain = load_summarize_chain(llm, chain_type="map_reduce")
    summary = chain.run(docs)   
    return summary

summarize = summarize_pdf("war_update.pdf")
print(summarize)

**Comment by MIDORIBIN** [comment]
@muhammadhasnain100 
Thanks for the report.

Could you share all error messages?
Also, could you share the pdf file if possible?

**Comment by MIDORIBIN** [comment]
@muhammadhasnain100 
My guess is that the Aichat rate limit is the cause of the error.
Please try another provider.

Based on your code, I have added a sample using "load_summarize_chain".
Please refer to it.
ca9c9aef0529464093f4ebf2524b75985b8b64fb

**Comment by muhammadhasnain100** [comment]
Thank You very much
