### ISSUE TITLE
This isn't an issue, but rather solving some problems that I had: '/Werror=incompatible-pointer-types' and 'C:\\Users\\Name\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Profile 1\\Network\\Cookies'

### ISSUE THREAD

**Issue by SomethingSimple4** [MIDORIBIN/langchain-gpt4free#4]
The first was this error on the C++ compiler: '/Werror=incompatible-pointer-types'
The second the was this: 'C:\\Users\\Name\\AppData\\Roaming\\..\\Local\\Google\\Chrome\\User Data\\Profile 1\\Network\\Cookies'

The first issue is solved by downloading this and then extracting it:  https://github.com/PetterS/quickjs/files/12180440/quickjs-1.19.2-cp311-cp311-win_amd64.zip
You then "pip install path-to-said-file"

The second issue is solved by simply closing Chrome completely.

I have to thank you guys very much for this. This will be very useful in my projects to come.

**Comment by MIDORIBIN** [comment]
@SomethingSimple4 
Thanks for the report!
